title: Soterolab
description: Laboratório para incentivar a democratização e descolonização do pensamento científico. 
tagline: teste
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman